--Q1
SELECT AVG(POPULATION_DENSITY), AREA_CLUSTER
FROM POLICY_FEATURES 
GROUP BY AREA_CLUSTER
ORDER BY AREA_CLUSTER;

--Q2
SELECT POLICY_ID, MAKE, SEGMENT, MODEL, NCAP_RATING
FROM CAR_FEATURES
WHERE ((NCAP_RATING > 4) AND POLICY_ID IN(SELECT POLICY_ID FROM POLICY_FEATURES WHERE ((POLICY_TENURE*10) > 5)) AND GROSS_WEIGHT<2000)
ORDER BY POLICY_ID;

--Q3
SELECT SEGMENT, COUNT(POLICY_ID)
FROM CAR_FEATURES
GROUP BY SEGMENT
HAVING COUNT(POLICY_ID)>100
ORDER BY COUNT(POLICY_ID) DESC;

--Q4
SELECT POLICY_ID, C.MAKE, C.MODEL, P.POLICY_TENURE
FROM CAR_FEATURES C
JOIN POLICY_FEATURES P
USING (POLICY_ID)
WHERE P.POLICY_TENURE IS NOT NULL
ORDER BY POLICY_TENURE DESC;

--Q6
SELECT * FROM(
SELECT C.MODEL, ROUND(AVG(P.POLICY_TENURE),4) AS AVG_POLICY_TENURE 
FROM POLICY_FEATURES P
JOIN CAR_FEATURES C
ON (P.POLICY_ID=C.POLICY_ID)
WHERE P.POLICY_ID IN
(SELECT POLICY_ID
FROM INSURANCE_CLAIM
WHERE IS_CLAIM =1)
GROUP BY C.MODEL
ORDER BY AVG(POLICY_TENURE) DESC)
WHERE ROWNUM<=3;
