SELECT AVG(POPULATION_DENSITY), AREA_CLUSTER
FROM POLICY_FEATURES 
GROUP BY AREA_CLUSTER
ORDER BY AREA_CLUSTER;

SELECT POLICY_ID, MAKE, SEGMENT, MODEL, NCAP_RATING
FROM CAR_FEATURES
WHERE ((NCAP_RATING > 4) AND POLICY_ID IN(SELECT POLICY_ID FROM POLICY_FEATURES WHERE ((POLICY_TENURE*10) > 5)) AND GROSS_WEIGHT<2000)
ORDER BY POLICY_ID;

SELECT SEGMENT, COUNT(POLICY_ID)
FROM CAR_FEATURES
GROUP BY SEGMENT
HAVING COUNT(POLICY_ID)>100;

SELECT POLICY_ID, MAKE, MODEL
FROM CAR_FEATURES
WHERE POLICY_ID IN (SELECT POLICY_ID FROM POLICY_FEATURES WHERE (POLICY_TENURE = MAX(POLICY_TENURE)));

